variables:
  SSHUSER: "backend"
  SSHPASS: "falah0918"
  SSHSERVER: "10.70.0.32"
  BRANCH: "$CI_COMMIT_REF_NAME"
  DOCKER_COMMAND: "docker compose up -d"
  REPOSITORY: "wushie"
  TAG_COMMIT: "$REPOSITORY/$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA"
  TAG_LATEST: "$REPOSITORY/$CI_PROJECT_NAME:latest"
  CI_REGISTRY_USER: "wushie"
  GIT_DEPTH: "0"
  FLUX_HTTPS_URL: "https://wush:$GIT_TOKEN@git.falahtech.com/wush/staging.git"

stages:
  - build

build:
  stage: build
  image: moby/buildkit:rootless
  variables:
    BUILDKITD_FLAGS: --oci-worker-no-process-sandbox
  before_script:
    - mkdir -p ~/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > ~/.docker/config.json
  script:
    - |
      buildctl-daemonless.sh build \
        --frontend dockerfile.v0 \
        --local context=. \
        --local dockerfile=. \
        --output type=image,name=$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA,push=true \
        --output type=image,name=$CI_REGISTRY_IMAGE:latest,push=true
  only:
    - develop
